name: Create issue on commit
on:
  issues:
    types: [opened]
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment on specific issue
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/7/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "body": "This is my automated comment! \n ${{ github.event }} -\ngithub.actor: ${{ github.actor }} -\n github.base_ref: ${{ github.base_ref }}-\n github.workflow: ${{ github.workflow }}-\ngithub.run_number: ${{ github.run_number }}-\n github.run_id: ${{ github.run_id }}-\n github.workspace: ${{ github.workspace }}-\n github.event: ${{ github.event }}-\n github.event_name: ${{ github.event_name }}-\n github.event_path: ${{ github.event_path }}-\n github.head_ref: ${{ github.head_ref }}-\n github.job: ${{ github.job }} -\n github.ref: ${{ github.ref }} -\n github.repository: ${{ github.repository }} -\n ----\n\n\njob: ${{ job }} \n job.container: ${{ job.container }} \n job.container.id: ${{ job.container.id }} \n job.container.network: ${{ job.container.network }} \n job.services: ${{ job.services }} \njob.status: ${{ job.status }} \n\n\n runner.os: ${{ runner.os }} \n runner.temp:${{ runner.temp }} \nrunner.tool_cache: ${{ runner.tool_cache }} \n MATRIX_CONTEXT: ${{ toJson(matrix) }} \n STRATEGY_CONTEXT: ${{ toJson(strategy) }}"
            }'